language: python
python:
  - "3.5"
  - "nightly"
addons:
  apt:
    packages:
      - gpg2
before_install:
  - mkdir -p ~/.config/avendesora
  - cp etc/* ~/.config/avendesora
  - cp avendesora/words ~/.config/avendesora
install:
  - pip install .
script: 
  - py.test tests
deploy:
    provider: pypi
    user: avendesora
    on:
        tags: true
