language: python
python:
  - "3.4"
  - "3.5"
  - "nightly"
before_install:
  - mkdir -p ~/.config/avendesora
  - cp etc/* ~/.config/avendesora
install:
  - pip install .
script: 
  - py.test tests
deploy:
    provider: pypi
    user: avendesora
    on:
        tags: true


