language: python
python:
  - "3.5"
  - "nightly"
addons:
  apt:
    packages:
      - gnupg
install:
  - pip install .
  - chmod -R go-rwx tests/home/gnupg
script: 
  - cd tests; py.test-3
deploy:
    provider: pypi
    user: avendesora
    on:
        tags: true
