language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
addons:
  apt:
    packages:
      - gnupg
install:
  - pip install scrypt coveralls pexpect
  - pip install .
  - chmod -R go-rwx tests/home/gnupg
script:
  - coverage run -m py.test
after_success:
  - coveralls
