language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly"
addons:
  apt:
    packages:
      - gnupg
install:
  - pip install scrypt coveralls
  - pip install .
  - chmod -R go-rwx tests/home/gnupg
script:
  - coverage run -m py.test
deploy:
    provider: pypi
    user: avendesora
    on:
        tags: true
after_success:
  - coveralls
