language: python
dist: focal
addons:
  apt:
    packages:
      - gnupg
      - libgirepository-dev
      - cairo
install:
  - pip install scrypt coveralls pexpect
  - pip install .
  - chmod -R go-rwx tests/home/gnupg
script:
  - coverage run -m py.test
after_success:
  - coveralls
jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9-dev
    - python: nightly
  allow_failures:
    - python: nightly
  fast_finish: true
