language: python
dist: focal
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - gnupg
      - libgirepository1.0-dev
install:
  - pip install scrypt coveralls pexpect
  - pip install .
  - chmod -R go-rwx tests/home/gnupg
script:
  - coverage run -m py.test
after_success:
  - coveralls
jobs:
  include:
    - python: 3.6
      os: linux
    - python: 3.7
      os: linux
    - python: 3.8
      os: linux
    - python: 3.9
      os: linux
    - python: 3.10-dev
      os: linux
    - python: nightly
      os: linux
    - python: 3.9
      os: osx
      language: generic
  allow_failures:
    - python: 3.10-dev
      os: linux
    - python: nightly
      os: linux
    - python: 3.9
      os: osx
      language: generic
  fast_finish: true
