language: python
dist: focal
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - gnupg
      - libgirepository1.0-dev
install:
  - pip install scrypt coveralls pexpect
  - pip install .
  - chmod -R go-rwx tests/home/gnupg
script:
  - coverage run -m py.test
after_success:
  - coveralls
jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
    - python: 3.10-dev
    - python: nightly
  allow_failures:
    - python: 3.10-dev
    - python: nightly
    - os: osx
  fast_finish: true
