#!/usr/bin/env bash

set nonomatch
rm -f avendesora.{1,3,5} avendesora.{1,3,5}.rst avendesora.{1,3,5}.pdf

# the rest is common to all python directories
rm -f *.pyc *.pyo .test*.sum expected result install.out
rm -rf build *.egg-info dist __pycache__ .coverage .coverage-html htmlcov
rm -rf home/.python-eggs
for i in */clean
do
    if [[ "$i" == '*/clean' ]]
    then
        break
    fi
    #echo $i
    ( cd ${i%/*}; ./clean )
done
for i in */Makefile
do
    if [[ "$i" == '*/Makefile' ]]
    then
        break
    fi
    #echo $i
    ( cd ${i%/*}; make clean )
done
