#!/usr/bin/env bash

set nonomatch

# the rest is common to all python directories
rm -f *.pyc *.pyo .test*.sum expected result install.out
rm -rf build *.egg-info dist **/__pycache__ .coverage .coverage-html htmlcov
rm -rf home/.python-eggs
