#!/usr/bin/env bash
# Set python variable to python executable you wish to use.
# May be python2 or python3.
python=python3

# Determine the version of python we are using.
vers=$($python -c 'import sys; print("%s.%s" % (sys.version_info[0], sys.version_info[1]))')
echo "Installing avendesora to ~/.local (Python$vers)."

# Remove build directories from a previous install to assure a clean install.
rm -rf build dist abraxas.egg-info install.out

# Install avendesora
$python setup.py install --quiet --user >& install.out
if [ $? -ne 0 ] ; then
    echo "Problems found, aborting (see install.out)"
    exit 1
fi

# Remove build directories, because I like a clean directory.
rm -rf build dist avendesora.egg-info
