name: Avendesora
on: [push, pull_request]
jobs:
  check-bats-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.6", "3.x"]
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-gpg@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-node@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pygobject
        run: sudo apt install libgirepository2.0-dev python3-gi
      - name: Install cairo
        run: sudo apt install libcairo2-dev pkg-config python3-dev
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install pycairo --no-binary pycairo
          pip install .
          pip install tox
          pip install coveralls
      - name: Run tests
        run: tox
      - name: Report test coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
        run: coveralls
